server:
  port: 8080

spring:
  application:
    name: basic-demo

  cache:
    type: redis
    cache-names: products
    multilevel:
      time-to-live: 5s
      local:
        max-size: 2000
        expiry-jitter: 40
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    io.github.suppie.spring.cache: TRACE
